name: Build
on: [push, pull_request]
jobs:
  build:
    name: compiling for esp8266
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Copy config
      run: cp ESP_clock/config{.template,}.h
    - name: Compile all
      uses: ArminJo/arduino-test-compile@v2
      with:
        sketch-names: "ESP_clock.ino"
        arduino-board-fqbn: esp8266:esp8266:nodemcuv2:eesz=4M1M,xtal=80
        platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
        required-libraries: NTPClient,DHT sensor library,LedControl,rc-switch,Time
