name: Build
on: [push, pull_request]
jobs:
  build:
    name: compiling for esp8266
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile all
      uses: ArminJo/arduino-test-compile@v2.4.1
      with:
        arduino-board-fqbn: esp8266:esp8266:huzzah:eesz=4M3M,xtal=80
        platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
        required-libraries: NTPClient,DHT sensor library,LedControl,rc-switch,Time
